### ISSUE TITLE
core dump because of closure function in redhat linux

### ISSUE THREAD

**Issue by haifenghuang** [yulon/clofn#1]
As the title says, when I compile the code,  there is no problem. But when I run a sample program, I got below output:

```
Clofn: could't change memory type of C.malloc allocated!
Clofn: could't change memory type of C.malloc allocated!
Segmentation fault (core dumped)
```

My OS:

```
$ uname -a
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nomi-san** [comment]
@haifenghuang 
To see the error, you must trace the error handle _while_.. or _after_ **_clofn_active_memory** proceed.

https://github.com/yulon/clofn/blob/6a159aa70586c813b71404328aec0bb97abd174f/clofn.h#L17-L22

In **Linux**, the function memory is activated by [**mprotect**](http://man7.org/linux/man-pages/man2/mprotect.2.html), in error case, this function returned -1, and error handle can be catch by [**errno**](http://man7.org/linux/man-pages/man3/errno.3.html).

You can see the errors list [**here**](http://man7.org/linux/man-pages/man2/mprotect.2.html#ERRORS).
```c
...
    static inline bool _clofn_active_memory(void *ptr, size_t size) {
        int ret, err;
        ret = mprotect(...) == 0;
        err = errno();
        // tracing
        return ret;
    }
...
```

**Comment by haifenghuang** [comment]
I printed the `errno`, it is `13`, which means `Permission denied`, even if I run the executable in `root` mode, same error occurred.

**Comment by haifenghuang** [comment]
BTW, My OS is a VM.

**Comment by haifenghuang** [comment]
I got it solved after I issue below commands:

```sh
[hhf@localhost tests]$ getenforce
Enforcing

[hhf@localhost tests]$ sudo setenforce 0
[sudo] password for hhf: 
[hhf@localhost wobj]$ getenforce
Permissive
```
